ClientWCF/Models/Prodotto.cs
using ClientWCF.ServiceReference1;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClientWCF.Models
{
    public class Prodotto
    {
        public int id { get; set; }
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Display(Name = "Produttore")]
        public int produttore { get; set; }
        [Display(Name = "Prezzo")]
        public float prezzo { get; set; }
        [Display(Name = "Categoria")]
        public int categoria { get; set; }
        [Display(Name="Quantità")]
        public int quantità { get; set; }
        [Display(Name = "Posizione")]
        public string posizione { get; set; }

        //metodo per convertire da server a client
        public void convertiServerToCLient(ProdottoServer ds)
        {
            this.id = ds.id;
            this.nome = ds.nome;
            this.produttore = ds.produttore;
            this.prezzo = ds.prezzo;
            this.categoria = ds.categoria;
            this.quantità = ds.quantita;
            this.posizione = ds.posizione;
        }

        //metodo per convertire da client a server
        public ProdottoServer convertiClientToServer()
        {

            ProdottoServer ds = new ProdottoServer();
            ds.id = this.id;
            ds.nome = this.nome;
            ds.produttore = this.produttore;
            ds.prezzo = this.prezzo;
            ds.categoria = this.categoria;
            ds.quantita = this.quantità;
            ds.posizione = this.posizione;
            return ds;
        }
    }
}

ClientWCF/Controllers/ProdottoController.cs
using ClientWCF.Models;
using ClientWCF.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientWCF.Controllers
{
    public class ProdottoController : Controller
    {
        // GET: Prodotto
        public ActionResult Index()
        {
            return View();
        }

        //recupera il prodotto che il dipendente vuole modificare e lo ritorna alla view
        public ActionResult AzioniProdotto(int id)
        {
            Prodotto p = new Prodotto();
            if (ModelState.IsValid)
            {
                //connessione col service
                try
                {
                    var wcf = new ServiceReference1.Service1Client();
                    //controllo che ritorni un prodotto
                    if (wcf.getProdById(id) == null)
                    {
                        throw new Exception("Impossibile trovare il prodotto con id: "+id);
                    }
                    else
                    {
                        //converto il prodotto da server a client
                        p.convertiServerToCLient(wcf.getProdById(id));

                        //Creo una lista di stringhe ed aggiungo posizione corrente del prodotto + quelle disponibili
                        List<String> posizioni = new List<string>();
                        posizioni.Add(p.posizione);
                        foreach(var z in wcf.getFreePos())
                        {
                            posizioni.Add(z);
                        }

                        //aggiungo le posizioni al viewbag.data
                        ViewBag.data = posizioni;
                        //aggiungo il nome del prodotto al viewbag.message
                        ViewBag.Message = p.nome;
                        //ritorno alla view passandogli il prodotto selezionato
                        return View(p);
                    }

                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("Error");
                }
            }
            ViewBag.Message = "Dati non consoni al Model specificato!";
            return View("Error");
        }

        //chiama il metodo del server per modificare il prodotto e ritorna alla lista prodotti aggiornata
        [HttpPost]
        public ActionResult AzioniProdotto(Prodotto p1)
        {
            if (ModelState.IsValid)
            {
                //connessione col service
                try
                {
                    var wcf = new ServiceReference1.Service1Client();
                    //recupero l'id del dipendente che vuole fare la modifica
                    int idDip = (int)Session["ID"];
                    //recupero la data attuale
                    string date = DateTime.UtcNow.AddHours(1).ToString("yyyy-MM-dd HH:mm:ss");

                    //controllo cosa è stato cambiato per metterlo nella descrizione
                    Prodotto p = new Prodotto();
                    p.convertiServerToCLient(wcf.getProdById(p1.id));
                    string cambiamenti = "";
                    if (p.quantità != p1.quantità) cambiamenti = "Quantità = " + p1.quantità + " ";
                    if (p.posizione != p1.posizione) cambiamenti = cambiamenti + "Posizione = " + p1.posizione;

                    //se non cambiamo niente torniamo alla lista dei prodotti
                    if (p.quantità == p1.quantità && p.posizione == p1.posizione) return RedirectToAction("Prodotti");

                    //convertiamo il model in un oggetto per il server
                    var ps = p1.convertiClientToServer();

                    //controllo che ritorni true
                    if (wcf.updateProduct(ps, idDip, cambiamenti, date))
                    {
                        //ritorno alla view prodotti tramite redirectToAction
                        return RedirectToAction("Prodotti");
                    }
                    else
                    {
                        throw new Exception("Impossibile aggiornare il prodotto!");
                    }

                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("Error");
                }
            }
            ViewBag.Message = "Dati non consoni al Model specificato!";
            return View("Error");
        }

        //recupero tutti i prodotti dal server e li passo alla view
        public ActionResult Prodotti()
        {
            ListaProdotti LP = new ListaProdotti();
            if (ModelState.IsValid)
            {
                //connessione col service
                try
                {
                    var wcf = new ServiceReference1.Service1Client();

                    //otteniamo la lista di categorie e la inseriamo in una combobox nella view
                    List<String> nomiCate = new List<string>();
                    foreach (var x in wcf.getNomiCategorie())
                    {
                        nomiCate.Add(x);
                    }
                    //aggiungo le categorie alla viewbag.nomiCate
                    ViewBag.nomiCate = nomiCate;

                    if (wcf.getListaProdotti() == null)
                    {
                        throw new Exception("Impossibile stampare i prodotti!");
                    }
                    else
                    {
                        //recupero la lista dei nomi delle categorie e la passo alla vista con viewbag.categorie
                        ViewBag.categorie = nomiCate;

                        //recupero la lista dei nomi dei produttori e la passo alla vista con viewbag.produttori
                        ViewBag.produttori = wcf.getNomiProduttori();

                        //converto la lista di prodotti da server a client
                        LP.ConvertServerList(wcf.getListaProdotti());
                        //ritorno alla view con la lista prodotti client
                        return View(LP);
                    }

                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("Error");
                }
            }
            ViewBag.Message = "Dati non consoni al Model specificato!";
            return View("Error");
        }

        //recupera tutti i prodotti della categoria selezionata e li passa alla view
        [HttpPost]
        public ActionResult Prodotti(String Categoria)
        {
            if (ModelState.IsValid)
            {
                //recupero il valore della categoria
                var selectedValue = Categoria;
                ListaProdotti LP = new ListaProdotti();

                //connessione col service
                try
                {
                    var wcf = new ServiceReference1.Service1Client();

                    //otteniamo la lista di categorie e la inseriamo in una combobox nella view
                    List<String> nomiCate = new List<string>();
                    foreach (var x in wcf.getNomiCategorie())
                    {
                        nomiCate.Add(x);
                    }
                    ViewBag.nomiCate = nomiCate;

                    //ottenialmo la lista di prodotti con categoria scelta
                    var prodByCat = wcf.getListaProdottiByCategory(int.Parse(selectedValue));

                    if (prodByCat == null)
                    {
                        throw new Exception("Impossibile stampare i prodotti!");
                    }
                    else
                    {
                        //recupero la lista dei nomi delle categorie e la passo alla vista con viewbag.categorie
                        ViewBag.categorie = nomiCate;

                        //recupero la lista dei nomi dei produttori e la passo alla vista con viewbag.produttori
                        ViewBag.produttori = wcf.getNomiProduttori();

                        //converto la lista prodotti da server a client
                        LP.ConvertServerList(prodByCat);
                        //ritorno la view con la lista prodotti client
                        return View(LP);
                    }

                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                    return View("Error");
                }
            }
            ViewBag.Message = "Dati non consoni al Model specificato!";
            return View("Error");
        }

        //recupera le categorie, i produttori ed i posti disponibili e li passa alla view
        public ActionResult CreaProdotto()
        {
            Prodotto p1 = new Prodotto();
            if (ModelState.IsValid)
            {
                //connessione col service
                try
                {
                    var wcf = new ServiceReference1.Service1Client();

                    //recupero i nomi delle categorie
                    List<String> nomiCat = new List<string>(); 
                    foreach(var x in wcf.getNomiCategorie())
                    {
                        nomiCat.Add(x);
                    }
                    ViewBag.nomiCat = nomiCat;

                    //recupero i nomi dei produttori
                    List<String> nomiProd = new List<string>();
                    foreach (var x in wcf.getNomiProduttori())
                    {
                        nomiProd.Add(x);
                    }
                    ViewBag.nomiProd = nomiProd;

                    //recupero i posti disponibili
                    List<String> posti = new List<string>();
                    foreach (var x in wcf.getFreePos())
                    {
                        posti.Add(x);
                    }
                    ViewBag.posti = posti;

ClientWCF/Views/Prodotto/AzioniProdotto.cshtml
@model ClientWCF.Models.Prodotto

@{
    ViewBag.Title = "Azioni Prodotto";
}

<h2>Azioni su prodotto @ViewBag.Message</h2>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.quantità, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.quantità, new { htmlAttributes = new { @class = "form-control", @min = "0" ,required = "required" } })
            @Html.ValidationMessageFor(model => model.quantità, "", new { @class = "text-danger" })
        </div>
    </div>


        <div class="form-group">
            @Html.LabelFor(model => model.posizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    foreach (var x in ViewBag.data)
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = x,
                            Value = x
                        });
                    }

                }

                @Html.DropDownListFor(model => model.posizione, listItems, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modifica" class="btn btn-default" />
            </div>
        </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClientWCF/Views/Prodotto/CreaProdotto.cshtml
@model ClientWCF.Models.Prodotto

@{
    ViewBag.Title = "CreaProdotto";
}

<h2>CreaProdotto</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prodotto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" ,required = "required" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.produttore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems = new List<SelectListItem>();
                    var cnt = 1;
                    foreach (var x in ViewBag.nomiProd)
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = x,
                            Value = cnt.ToString()
                        });
                        cnt++;
                    }
                }
                @Html.DropDownListFor(model => model.produttore, listItems, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezzo, new { htmlAttributes = new { @class = "form-control" ,required = "required" } })
                @Html.ValidationMessageFor(model => model.prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems2 = new List<SelectListItem>();
                    var cnt2 = 1;
                    foreach (var x in ViewBag.nomiCat)
                    {
                        listItems2.Add(new SelectListItem
                        {
                            Text = x,
                            Value = cnt2.ToString()
                        });
                        cnt2++;
                    }
                }
                @Html.DropDownListFor(model => model.categoria, listItems2, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantità, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantità, new { htmlAttributes = new { @class = "form-control", @min = "1" ,required = "required" } })
                @Html.ValidationMessageFor(model => model.quantità, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.posizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    List<SelectListItem> listItems3 = new List<SelectListItem>();
                    foreach (var x in ViewBag.posti)
                    {
                        listItems3.Add(new SelectListItem
                        {
                            Text = x,
                            Value = x
                        });
                    }
                }
                @Html.DropDownListFor(model => model.posizione, listItems3, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ClientWCF/Views/Prodotto/EliminaProdotto.cshtml
@model ClientWCF.Models.Prodotto

@{
    ViewBag.Title = "EliminaProdotto";
}

<h2>Elimina Prodotto</h2>

<h3>Sei sicuro di voler eliminare questo prodotto? Eliminarai anche tutte le operazioni relative ad esso!</h3>
<div>
    <h4>Prodotto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.produttore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.produttore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prezzo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prezzo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantità)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantità)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.posizione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.posizione)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

ClientWCF/Views/Prodotto/ModificaProdotto.cshtml
@model ClientWCF.Models.Prodotto

@{
    ViewBag.Title = "ModificaProdotto";
}

<h2>ModificaProdotto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Prodotto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.produttore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ List<SelectListItem> listItems = new List<SelectListItem>();
                    var cnt = 1;
                    foreach (var x in ViewBag.nomiProd)
                    {
                        listItems.Add(new SelectListItem
                        {
                            Text = x,
                            Value = cnt.ToString()
                        });
                        cnt++;
                    } }
                @Html.DropDownListFor(model => model.produttore, listItems, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prezzo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezzo, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.prezzo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ List<SelectListItem> listItems2 = new List<SelectListItem>();
                    var cnt2 = 1;
                    foreach (var x in ViewBag.nomiCat)
                    {
                        listItems2.Add(new SelectListItem
                        {
                            Text = x,
                            Value = cnt2.ToString()
                        });
                        cnt2++;
                    } 
                    
                }
                @Html.DropDownListFor(model => model.categoria, listItems2, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantità, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantità, new { htmlAttributes = new { @class = "form-control", @min = "0", required = "required" } })
                @Html.ValidationMessageFor(model => model.quantità, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.posizione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ List<SelectListItem> listItems3 = new List<SelectListItem>();
                    foreach (var x in ViewBag.posti)
                    {
                        listItems3.Add(new SelectListItem
                        {
                            Text = x,
                            Value = x
                        });
                    } }
                @Html.DropDownListFor(model => model.posizione, listItems3, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ClientWCF/Views/Prodotto/Prodotti.cshtml
@model ClientWCF.Models.ListaProdotti
@{
    ViewBag.Title = "Prodotti";
}

<h2>Prodotti</h2>

<b>Ricerca per categoria</b>
@using (Html.BeginForm("Prodotti", "Prodotto", FormMethod.Post))
{
    <br>
    <div class="col-md-10">
        @{ List<SelectListItem> listItems2 = new List<SelectListItem>();
            var cnt2 = 1;
            foreach (var x in ViewBag.nomiCate)
            {
                listItems2.Add(new SelectListItem
                {
                    Text = x,
                    Value = cnt2.ToString()
                });
                cnt2++;
            }
        }
        @Html.DropDownList("Categoria", listItems2, new { @class = "form-control" })
        <br>
        <input type="submit" value="Cerca" class="btn btn-default" />
    </div>
    <br>
    <br>
    <br>
}
<br>
<br>
<br>

<table width="100%">
    <tr>
        <th style="text-align:center">ID</th>
        <th style="text-align:center">Nome</th>
        <th style="text-align:center">Prezzo</th>
        <th style="text-align:center">Produttore</th>
        <th style="text-align:center">Categoria</th>
        <th style="text-align:center">Quantità</th>
        <th style="text-align:center">Posizione</th>
        <th style="text-align:center">Modifica</th>
        @if ((int)Session["CEO"] == 1)
        {
            <th style="text-align:center">Elimina</th>
        }
    </tr>
    @{foreach (var i in Model.listaProducts)
        {
            <tr style="text-align:center">
                <td>
                    @i.id
                </td>
                <td>
                    @i.nome
                </td>
                <td>
                    €@i.prezzo
                </td>
                <td>
                    @ViewBag.produttori[i.produttore - 1]
                </td>
                <td>
                    @ViewBag.categorie[i.categoria - 1]
                </td>
                <td>
                    @i.quantità
                </td>
                <td>
                    @i.posizione
                </td>
                @if ((int)Session["CEO"] == 1)
                {
                    <td>
                        @Html.ActionLink("Modifica", "ModificaProdotto", new { id = i.id })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Modifica", "AzioniProdotto", new { id = i.id })
                    </td>
                }

                @if ((int)Session["CEO"] == 1)
                {
                    <td>
                        @Html.ActionLink("Elimina", "EliminaProdotto", new { id = i.id })
                    </td>
                }
            </tr>
        }
    }
</table>